name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  android-test:
  
      runs-on: ubuntu-latest
      
      steps:
        - uses: reactivecircus/android-emulator-runner@v2
          name: Run instrumented tests
          with:
            api-level: 23
            target: default
            arch: x86
            profile: Nexus 6
            script: ./gradlew connectedCheck --stacktrace
