name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
      
  android-test:
  
      runs-on: ubuntu-latest
      
      steps:
        - uses: actions/checkout@v2
        - uses: reactivecircus/android-emulator-runner@v2
          name: Run tests with coverage
          with:
            api-level: 23
            target: default
            arch: x86
            profile: Nexus 6
            script: ./gradlew jacocoTestReport
        - name: Remove build.gradle
          run: rm build.gradle
        - name: SonarCloud Scan
          uses: sonarsource/sonarcloud-github-action@master
          env:
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            args: >
              -Dsonar.coverage.jacoco.xmlReportPaths=app/build/reports/jacoco/jacocoTestReport/jacocoTestReport.xml
              -Dsonar.projectKey=testing_demo:main
              -Dsonar.sources=app/src/main/java
              -Dsonar.host.url=https://ec.cs.hm.edu
              -Dsonar.branch.name=main
